#184347019 implementing logout functionality
atlp-rwanda/vikings-ec-bn pull request #14
Opened 2023-02-08 13:03 UTC by fabmukunzi

#### What does this PR do?
Create logout endpoint

#### Description of Task to be completed?

- [ ] Creates logout.controller.js file in controllers
- [ ] Creates token.service.js file in services
- [ ] Stores a jwt token in the jwtTokens relation as long as token is generated
- [ ] Invalidates the token by changing token revoke status to true

#### How should this be manually tested?

1. Clone [repo](https://github.com/atlp-rwanda/vikings-ec-bn.git)
2. Change into the directory **vikings-ec-bn**
3. Checkout to this branch: `feature/user-logout-184347019`
4. Run the command `npm install` to install dependencies
5. Run `npm run migrate`
6.Run `npm run dev`
7.In postman create a post request `localhost:5000/api/v1/users/logout`

#### What are the relevant pivotal tracker stories?

[#184347019](https://www.pivotaltracker.com/story/show/184347019)

2023-02-09 11:34 UTC, Fidela1 approved these changes

2023-02-09 11:38 UTC, Abdden approved these changes

2023-02-09 12:05 UTC, irakozetony approved these changes

2023-02-09 13:53 UTC, ndatumuremyi approved these changes

2023-02-10 08:52 UTC, ncutixavier requested changes
All checks should be passed

2023-02-10 08:52 UTC, ncutixavier commented on src/middlewares/auth.middleware.js
> +export const verifyToken = async(req, res, next) => {
Rename this to `protectRoute`

2023-02-10 08:52 UTC, ncutixavier commented on src/controllers/logout.controller.js
> +}
- Follow the same convention applied in the user controller

2023-02-10 08:52 UTC, ncutixavier commented on src/middlewares/auth.middleware.js
> +    }
Let's enforce to have a proper error message

2023-02-10 08:52 UTC, ncutixavier commented on src/services/token.service.js
> +        // }
Remove all unnecessary comments

2023-02-10 08:52 UTC, ncutixavier commented on src/utils/functions.util.js
> +}
- Don't use dataValues 'cause it's not necessary. Ask Yves for help
- Rename this file

2023-02-10 17:15 UTC, ncutixavier approved these changes

2023-02-10 17:16 UTC, merged