feature src: added password update endpoint
atlp-rwanda/vikings-ec-bn pull request #16
Opened 2023-02-08 15:05 UTC by Abdden

[Finishes #184347027]

#### What does this PR do?

Creates the update password endpoint

#### Description of Task to be completed?

- [x] Build the user password update endpoint in the project
- [x] Create password update tests
- [x] Add password update route in swagger docs

#### How should this be manually tested?

1. Clone [repo](https://github.com/atlp-rwanda/vikings-ec-bn.git)
2. Change into the directory vikings-ec-bn
3. Checkout to this branch: `feature/user-login-184347020`
4. Run the command `npm install` to install dependencies
5. Run `npm run migrate:reset`
6. Go to the `http://localhost:<port>/api-docs` URL in your browser or `http://localhost:<port>/api/v1/users/update` in Postman

#### What are the relevant pivotal tracker stories?

[#184347027](https://www.pivotaltracker.com/story/show/184347027)

2023-02-09 12:03 UTC, irakozetony approved these changes

2023-02-09 17:27 UTC, ndatumuremyi approved these changes

2023-02-09 22:32 UTC, irakozetony approved these changes

2023-02-10 07:22 UTC, ndatumuremyi approved these changes

2023-02-10 08:27 UTC, ncutixavier requested changes
- For authentication middleware you have to wait for logout task

2023-02-10 08:27 UTC, ncutixavier commented on .vscode/settings.json
> +}
Put this file gitignore

2023-02-10 08:27 UTC, ncutixavier commented on src/controllers/user.controller.js
> +      return res.status(201).json({ success: 'Updated successfully' });
Correct the response
- Status code should success, because you're not creating
- Change the key of your response
- Update your message

2023-02-10 08:27 UTC, ncutixavier commented on src/routes/api/user.routes.js
> +  '/password-update',
change route to `/update-password`

2023-02-10 08:27 UTC, ncutixavier commented on src/utils/bcrypt.util.js
> +    console.log(password);
Remover all logs

2023-02-10 08:27 UTC, ncutixavier commented on src/services/user.service.js
> +  }
Replace key with id

2023-02-10 08:53 UTC, Munezeroolivierhugue approved these changes

2023-02-13 08:33 UTC, ndatumuremyi approved these changes

2023-02-13 08:43 UTC, irakozetony approved these changes

2023-02-13 09:17 UTC, nshimiyejayd approved these changes

2023-02-13 17:38 UTC, ncutixavier requested changes

2023-02-13 17:38 UTC, ncutixavier commented on src/middlewares/user.middleware.js
> +  static async updatePassword(req, res, next) {
Rename this middleware

2023-02-13 17:38 UTC, ncutixavier commented on src/services/user.service.js
> +  }
This service should be reusable for updating user info. Instead of passing only a password, you can allow passing multiple data.

2023-02-13 19:09 UTC, ncutixavier approved these changes

2023-02-13 19:11 UTC, merged