feature src: added google login authentication endpoint
atlp-rwanda/vikings-ec-bn pull request #17
Opened 2023-02-08 23:12 UTC by Abdden

#### What does this PR do?

Creates the google login authentication endpoint

#### Description of Task to be completed?

- [x] Create the google login functionality in the project.

#### How should this be manually tested?

1. Clone [repo](https://github.com/atlp-rwanda/vikings-ec-bn.git)
2. Change into the directory vikings-ec-bn
3. Checkout to this branch: `feature/google-auth-184347021`
4. In your `.env` file, create a `SECRET_TOKEN` variable with a value in it
5. Run the command `npm install` to install dependencies
6. Go to the `http://localhost:<port>/api/v1/users/auth/google` URL in your browser

#### What are the relevant pivotal tracker stories?

[#184347021](https://www.pivotaltracker.com/story/show/184347021)

2023-02-09 09:20 UTC, nshimiyejayd approved these changes

2023-02-09 11:34 UTC, fabmukunzi approved these changes

2023-02-09 12:04 UTC, irakozetony approved these changes

2023-02-09 12:21 UTC, ndatumuremyi approved these changes

2023-02-13 08:32 UTC, ndatumuremyi approved these changes

2023-02-13 08:43 UTC, nshimiyejayd approved these changes

2023-02-13 08:44 UTC, irakozetony approved these changes

2023-02-13 09:33 UTC, ncutixavier requested changes

2023-02-13 09:33 UTC, ncutixavier commented on src/controllers/logout.controller.js
> +    await logoutService.revokeToken(data).then(() => {
- Don't use await and then
- Since you're using try and catch, use only await

2023-02-13 09:33 UTC, ncutixavier commented on src/controllers/user.controller.js
> +    return res.redirect(`/api/v1/users/redirect?guru=${token}`);
Why `guru`?

2023-02-13 12:43 UTC, ncutixavier approved these changes

2023-02-13 12:43 UTC, merged