feature profile-settings
atlp-rwanda/vikings-ec-bn pull request #19
Opened 2023-02-10 07:49 UTC by ndatumuremyi

### What does this PR do?

get and update the user Profile
### Description of Task to be completed?

- [x] Implement user Profile settings

### How should this be manually tested?

1. Clone [repo](https://github.com/atlp-rwanda/vikings-ec-bn.git)
2. Change into the directory vikings-ec-bn
3. Checkout to this branch: `feature/profile-settings-184347024`
4. In your `.env` file, create a `CLOUD_NAME,CLOUD_API_KEY,CLOUD_API_SECRET` variable with a value in it
5. Run the command `npm install` to install all packages
6. Run `npm run reset:db` to reset database
7. Go to the `http://localhost:<port>/api-docs/#/Profile/patch_api_v1_users_profile` URL in your browser or `http://localhost:<port>/api/v1/users/profile` in Postman

### What are the relevant pivotal tracker stories?

[#184347024](https://www.pivotaltracker.com/story/show/184347024)

2023-02-13 08:51 UTC, Abdden approved these changes

2023-02-13 09:29 UTC, irakozetony approved these changes
Looks good to me!

2023-02-13 09:35 UTC, Aline096 approved these changes

2023-02-13 12:20 UTC, ncutixavier requested changes

2023-02-13 12:20 UTC, ncutixavier commented on src/controllers/profile.controller.js
> +			}else {
Put this in user controller

2023-02-13 12:20 UTC, ncutixavier commented on src/routes/api/profile.routes.js
> +export default router;
This should be is user routes

2023-02-13 12:20 UTC, ncutixavier commented on src/routes/index.js
> +routes.use('/users/profile', profileRoutes);
GET .../users/profile
PUT .../users/profile

2023-02-13 12:20 UTC, ncutixavier commented on src/services/profile.service.js
> +}
Remove this service, and create two services in the user service file
- get by is
- update user

2023-02-13 12:20 UTC, ncutixavier commented on src/utils/cludinary.js
> +                {
- Let's have a method to upload the image
- Rename file

2023-02-13 14:22 UTC, ncutixavier requested changes

2023-02-13 14:22 UTC, ncutixavier commented on src/controllers/user.controller.js
> +                data:user
Just add only `user`

2023-02-13 14:22 UTC, ncutixavier commented on src/controllers/user.controller.js
> +        }
Replicate the catch block from the register, and do it on other catch block you wrote

2023-02-13 14:22 UTC, ncutixavier commented on src/controllers/user.controller.js
> +            return res.status(200).json({ message: 'updated successful', data: others });
Since we have endpoint to return user profile, return only message after updating profile

2023-02-13 14:22 UTC, ncutixavier commented on src/routes/api/user.routes.js
> +import verifyToken from '../../middlewares/auth.middleware';
I think the middleware called `protectRoute`

2023-02-13 14:22 UTC, ncutixavier commented on src/utils/cludinary.util.js
> +        });
- Change the status code
- file should be `cloudinary....js`

2023-02-13 14:22 UTC, ncutixavier commented on tests/profile/profile.test.js
> +// eslint-disable-next-line no-undef
Why are u disabling eslint instead of fixing it?

2023-02-14 15:30 UTC, ncutixavier requested changes

2023-02-14 15:30 UTC, ncutixavier commented on src/utils/cloudinary.util.js
> +// const app = express();
Remove all unnecessary comments

2023-02-14 15:30 UTC, ncutixavier commented on tests/profile/profile.test.js
> +		console.log('res.body',res.body);
Remove all logs

2023-02-14 15:43 UTC, ncutixavier approved these changes

2023-02-14 15:43 UTC, merged