#184347008 setup unit testing
atlp-rwanda/vikings-ec-bn pull request #2
Opened 2023-01-30 19:20 UTC by fabmukunzi

### What does this PR do?
Setting up unit testing with jest

### Description of Task to be completed?
Setting up jest to be used for unit testing

 ### How should this be manually tested?
1. Clone [repo](https://github.com/atlp-rwanda/vikings-ec-bn.git)
2. Change into the directory **vikings-ec-bn**
3. Checkout to this branch  **chore/setup-unit-testing-184347008**
4. Run the command `npm install` to install dependencies
6. Run the command `npm test
`
 ### What are the relevant pivotal tracker stories?
[184347008](https://www.pivotaltracker.com/story/show/184347008)

2023-01-30 19:48 UTC, Abdden approved these changes

2023-01-31 11:13 UTC, nshimiyejayd approved these changes

2023-02-01 08:58 UTC, Fidela1 approved these changes

2023-02-01 14:18 UTC, ncutixavier requested changes
- Resolve conflicts
- Recheck your PR title, ask @irakozetony 
- Coverage folder should be in `gitignore` 
- Update `gitignore` file by referring to this link https://raw.githubusercontent.com/github/gitignore/master/Node.gitignore

2023-02-01 20:21 UTC, closed without merging