#184347028 create user product
atlp-rwanda/vikings-ec-bn pull request #21
Opened 2023-02-13 16:20 UTC by fabmukunzi

### What does this PR do?
Allows a seller to create product

### Description of Task to be completed?

- [x] Creates product.controller.js file in controllers
- [x] Creates product.service.js file in services
- [x] Stores a Product in the Products relation

### How should this be manually tested?

1. Clone [repo](https://github.com/atlp-rwanda/vikings-ec-bn.git)
2. Change into the directory **vikings-ec-bn**
3. Checkout to this branch: `feature/create-product-184347028`
4. Run the command `npm install` to install packages
5. Run `npm run reset:db`
6.Run `npm run dev`
7.In postman create a post request `localhost:5000/api/v1/user/product`

### What are the relevant pivotal tracker stories?
[#184347028](https://www.pivotaltracker.com/story/show/184347028)

2023-02-15 11:09 UTC, Abdden approved these changes

2023-02-15 12:46 UTC, irakozetony approved these changes

2023-02-15 14:46 UTC, Munezeroolivierhugue approved these changes

2023-02-16 15:20 UTC, TuyizeeAnastase commented on src/validations/product/product.validation.js
> +    const category=req.body.category
check case-sensitive for category. first convert into lower letter

2023-02-16 15:20 UTC, TuyizeeAnastase commented on src/middlewares/product.middleware.js
> +  const cat = await Categories.findOne({where:{name:req.body.category}});
apply case-sensitive

2023-02-16 15:20 UTC, TuyizeeAnastase commented on src/controllers/category.controller.js
> +            name: req.body.category,
case-sensitive here( convert into lower letter before saving)

2023-02-16 15:20 UTC, TuyizeeAnastase commented on src/controllers/product.controller.js
> +      const { url } = await uploadPhoto(req, res, req.files.images[i]);
Which  file are allowed to upload ? what if i upload pdf ? you need to validate this.

2023-02-17 05:11 UTC, TuyizeeAnastase approved these changes

2023-02-17 05:56 UTC, Aline096 approved these changes

2023-02-17 08:08 UTC, ncutixavier requested changes

2023-02-17 08:08 UTC, ncutixavier commented on src/controllers/category.controller.js
> +        return res.status(500).json({message:'error while creating a category'});
The catch block should follow the same convention used in user control, ask Yves

2023-02-17 08:08 UTC, ncutixavier commented on src/controllers/category.controller.js
> +          };
- this line of code is confused
- the field used in the model should match with the `req.body`

2023-02-17 08:08 UTC, ncutixavier commented on src/controllers/product.controller.js
> +    }
- You need to have middleware to check file extensions, you can refer to `restrictTo` middleware
- After, have a middleware to upload images

2023-02-17 08:08 UTC, ncutixavier commented on src/controllers/product.controller.js
> +    console.log(images);
Remove all logs

2023-02-17 08:08 UTC, ncutixavier commented on src/controllers/product.controller.js
> +    }
Let have this as middleware before uploading images

2023-02-17 08:08 UTC, ncutixavier commented on src/controllers/product.controller.js
> +    .json({ message: 'Error occured while creating a product'});
Follow the same convention used before in catch block

2023-02-17 08:08 UTC, ncutixavier commented on src/middlewares/product.middleware.js
> +
This is category middleware not product

2023-02-17 08:08 UTC, ncutixavier commented on src/middlewares/user.middleware.js
> +};
We have middleware to check user role before accessing any route, check the router to get all users

2023-02-17 08:08 UTC, ncutixavier commented on src/routes/api/product.routes.js
> +productRoutes.post('/products',protectRoute,isSeller,productValidation,validateCategory,createProduct);
- Why do you have `validate category`?
- I can't see middleware to check the duplicate product
- Missing a middleware to check if category exist

2023-02-17 08:08 UTC, ncutixavier commented on src/routes/api/product.routes.js
> +productRoutes.post('/category',protectRoute,checkIfCategoryExists,addCategory);
I can't see validation for category

2023-02-17 08:08 UTC, ncutixavier commented on src/services/user.service.js
> +  static async updateUser(id, fields) {
Why are changing this?

2023-02-17 08:08 UTC, ncutixavier commented on src/validations/product/product.validation.js
> +};
This is middleware, not validation. We need to have validation for category separated with product

2023-02-17 08:08 UTC, ncutixavier commented on tests/products/product.test.js
> +/* eslint-disable no-undef */
Why are you disabling eslint instead of fixing it?

2023-02-17 08:39 UTC, ncutixavier requested changes

2023-02-17 08:39 UTC, ncutixavier commented on src/controllers/user.controller.js
> +      await UserService.updateUser(user.id);
You're not allowed to change this

2023-02-17 14:24 UTC, TuyizeeAnastase requested changes

2023-02-17 14:24 UTC, TuyizeeAnastase commented on src/middlewares/product.middleware.js
> +  if (getProduct) res.status(404).json({ message: 'Product already exists' });
use status code 400( 404 means not found)

2023-02-17 14:24 UTC, TuyizeeAnastase commented on src/middlewares/product.middleware.js
> +};
what happens when the extension is invalid?  try to add an else condition to throw an error

2023-02-17 14:24 UTC, TuyizeeAnastase commented on src/middlewares/product.middleware.js
> +    res.status(400).json({message:'No image given'});
change message body to `Please upload images`

2023-02-17 16:25 UTC, TuyizeeAnastase approved these changes

2023-02-17 19:46 UTC, ncutixavier requested changes

2023-02-17 19:46 UTC, ncutixavier commented on src/controllers/product.controller.js
> +    };
Since we have validation, you can refactor this code by using the spread operator. It's not necessary to mention the fields.

2023-02-17 19:46 UTC, ncutixavier commented on src/middlewares/category.middleware.js
> +      where: { name: req.body.name.toLowerCase() },
Let's inforce destructuring operator

2023-02-17 19:46 UTC, ncutixavier commented on src/middlewares/category.middleware.js
> +    if (categories) return res.status(400).json({ message: 'Category Already Exists!' });
Do not capitalise the message

2023-02-17 19:46 UTC, ncutixavier commented on src/middlewares/product.middleware.js
> +};
You need to implement two separate middleware.
- Checking the extensions
- uploading an image
- Refer to the code below on how to get file extension in node js
![image](https://user-images.githubusercontent.com/51375428/219770578-80e04e91-a7c1-4a22-9da2-cedd9048fc49.png)

2023-02-17 19:46 UTC, ncutixavier commented on src/middlewares/product.middleware.js
> +};
This should happens before uploading images

2023-02-17 19:46 UTC, ncutixavier commented on src/middlewares/product.middleware.js
> +};
- This is category middleware, not product middleware.
- Enforce destructuring assignment operator
- Your message should not be capitalize

2023-02-17 19:46 UTC, ncutixavier commented on src/middlewares/product.middleware.js
> +};
This is not necessary

2023-02-17 19:46 UTC, ncutixavier commented on src/validations/product/category.validation.js
> +    });
- How do you know if the category provided is invalid if you have not specified the valid category?
- Please check how the other validations are written

2023-02-17 19:46 UTC, ncutixavier commented on src/validations/product/product.validation.js
> +    });
Check the other validation are implemented. For example, in the user validation

2023-02-19 10:05 UTC, closed without merging