#184347025 disable an account
atlp-rwanda/vikings-ec-bn pull request #23
Opened 2023-02-14 12:26 UTC by Aline096

#### What does this PR do?
Admin should be able to disable an account 
#### Description of Task to be completed?
Due to varying reasons e.g fraud, abuse, malicious use or violation of terms of service, admin should be able to disable any user account. 
#### How should this be manually tested?
1. Checkout to this branch: feature/disable-account-184347025
2. Run the command `npm install`
3. Open browser and visit http://localhost:5000/api-docs/#/
4. Test functionalities of users / update status endpoint
#### What are the relevant pivotal tracker stories?
[184347025](https://www.pivotaltracker.com/story/show/184347025)

2023-02-15 07:38 UTC, ndatumuremyi approved these changes

2023-02-15 07:39 UTC, irakozetony approved these changes

2023-02-15 08:49 UTC, ncutixavier requested changes

2023-02-15 08:49 UTC, ncutixavier commented on src/controllers/user.controller.js
> +      });
You have to rename the method name and the success message, because this is about to disable account not update status

2023-02-15 08:49 UTC, ncutixavier commented on src/database/models/user.js
> +			},
this field should be a boolean, not a string. Hint: name it `isActive`

2023-02-15 08:49 UTC, ncutixavier commented on src/validations/user/status.validation.js
> +      .valid('active', 'disactive')
Field should be boolean

2023-02-15 10:37 UTC, ncutixavier requested changes

2023-02-15 10:37 UTC, ncutixavier commented on src/database/migrations/20230206125837-create-user.js
>        },
I still see isActive as String

2023-02-15 10:37 UTC, ncutixavier commented on src/validations/user/status.validation.js
> +      .valid(true,false)
Valid is not necessary when validating boolean

2023-02-16 09:10 UTC, Abdden approved these changes

2023-02-16 11:13 UTC, ncutixavier approved these changes

2023-02-16 11:13 UTC, merged