#184347032 list all products
atlp-rwanda/vikings-ec-bn pull request #30
Opened 2023-02-20 15:53 UTC by fabmukunzi

### What does this PR do?

Allows a user to retrieve all products

### Description of Task to be completed?

Check if a user is a seller or admin and give him only products in his collection
Otherwise display all products to the user

### How should this be manually tested?

1. Clone [repo](https://github.com/atlp-rwanda/vikings-ec-bn.git)
2. Change into the directory **vikings-ec-bn**
3. Checkout to this branch: `feature/list-all-products-184347032`
4. Run the command `npm install` to install packages
5. Run `npm run reset:db`
6.Run `npm run dev`
7.In postman create a get request `localhost:5000/api/v1/user/product`

### What are the relevant pivotal tracker stories?
[#184347032](https://www.pivotaltracker.com/story/show/184347032)

2023-02-20 20:24 UTC, TuyizeeAnastase requested changes

2023-02-20 20:24 UTC, TuyizeeAnastase commented on src/controllers/product.controller.js
> +    res.status(200).json({products:products})
- use try and catch block
- and send only one successful response

2023-02-20 20:31 UTC, irakozetony approved these changes

2023-02-20 21:00 UTC, TuyizeeAnastase requested changes

2023-02-20 21:00 UTC, TuyizeeAnastase commented on src/controllers/product.controller.js
> +    }
send only one response to refer to this:

`let products = await ProductService.getAllProducts();
if(condition){
    products=products.filter((product) => product.userId == id);
  }
return res.status(200).json({
   //send products in json here
})`

2023-02-21 05:45 UTC, ndatumuremyi approved these changes

2023-02-21 07:55 UTC, TuyizeeAnastase approved these changes

2023-02-21 14:33 UTC, TuyizeeAnastase requested changes

2023-02-21 14:33 UTC, TuyizeeAnastase commented on src/services/product.service.js
> +  }
use include to get all related entities to products

2023-02-21 16:54 UTC, TuyizeeAnastase requested changes

2023-02-21 16:54 UTC, TuyizeeAnastase commented on src/services/product.service.js
> +          ]
Nothing to exclude here in category

2023-02-21 16:54 UTC, TuyizeeAnastase commented on src/services/product.service.js
> +              'gender',
exclude only password and authcode

2023-02-22 09:51 UTC, TuyizeeAnastase requested changes

2023-02-22 09:51 UTC, TuyizeeAnastase commented on src/controllers/product.controller.js
> +    const { paginate } = req.query;
check what is limit and offset in pagination and use them here.

2023-02-22 09:51 UTC, TuyizeeAnastase commented on src/services/product.service.js
> +  }
check how findAllAndCount() function work for pagination

2023-02-22 17:13 UTC, Aline096 approved these changes

2023-02-22 17:16 UTC, Abdden approved these changes

2023-02-22 20:40 UTC, TuyizeeAnastase approved these changes

2023-02-23 09:17 UTC, ncutixavier approved these changes

2023-02-23 09:18 UTC, merged