feat: remove expired product
atlp-rwanda/vikings-ec-bn pull request #31
Opened 2023-02-21 19:30 UTC by Aline096

#### What does this PR do?
The products should stop listing if the expiry date has passed

#### Description of Task to be completed?
Given the expiration date has passed, the product should be removed from
the list of available products
#### How should this be manually tested?
1. Checkout to this branch: feature/delist-expired-products-184347045
2. Run the command npm install to install packages
3. Run `npm run dev`
4. Check functionalities of cron job for removing expired products
#### What are the relevant pivotal tracker stories?
[184347045](https://www.pivotaltracker.com/story/show/184347045)

2023-02-22 20:10 UTC, irakozetony approved these changes

2023-02-22 21:12 UTC, TuyizeeAnastase requested changes

2023-02-22 21:12 UTC, TuyizeeAnastase commented on src/controllers/product.controller.js
> +    const productId = req.params.productId;
use destructuring assignment

2023-02-22 21:12 UTC, TuyizeeAnastase commented on src/controllers/product.controller.js
> +        message: 'Failed to remove product from list',
message:"Failed to remove expired product from list

2023-02-22 21:12 UTC, TuyizeeAnastase commented on src/routes/api/product.routes.js
> +);
- Here you need middleware to check if the product exists
- and middleware to check if the seller is the owner of the product

2023-02-22 21:12 UTC, TuyizeeAnastase commented on src/services/delistExpiredProduct.service.js
> +            const isExpired =product.isExpired = true;
what is the use of this line of code

2023-02-24 09:20 UTC, ncutixavier requested changes

2023-02-24 09:20 UTC, ncutixavier commented on src/routes/api/product.routes.js
> +  '/:productId',
Change route to `/:productId/expired`

2023-02-24 09:20 UTC, ncutixavier commented on src/middlewares/product.middleware.js
> +  }
Use `protectRoute` to get logged in user

2023-02-24 09:20 UTC, ncutixavier commented on src/services/delistExpiredProduct.service.js
> +            const isExpired = product.isExpired = true;
Refactor this line

2023-02-24 09:20 UTC, ncutixavier commented on src/utils/mailTemplates.util.js
> +};
Update this message

2023-02-24 11:15 UTC, closed without merging