Feature/available product 184347029
atlp-rwanda/vikings-ec-bn pull request #33
Opened 2023-02-22 09:00 UTC by Fidela1

#### What does this PR do?

1. Allow Seller to mark available product
2. Allow seller to update and delete product

#### Description of Task to be completed?

- [x] Mark available product
- [x] Delete product
- [x] Update product

#### How should this be manually tested?

1. clone [repo](url)
2. Change into the directory vikings-ec-bn
3. Checkout to this branch `feature/available-product-184347029`
4. Run command `npm install`
5. Run `npm  run dev`
6. Open browser and visit http://localhost:5000/api-docs/#/
7. Test functionalities of product/ update product, delete product and mark available product

#### What are the relevant pivotal tracker stories?

[184347029](https://www.pivotaltracker.com/story/show/184347029)
[184347030](https://www.pivotaltracker.com/story/show/184347030)
[184347033](https://www.pivotaltracker.com/story/show/184347033)

2023-02-23 15:54 UTC, TuyizeeAnastase requested changes

2023-02-23 15:54 UTC, TuyizeeAnastase commented on src/controllers/product.controller.js
> +    const isAvailable = req.body.isAvailable;
use destructuring assignment

2023-02-23 15:54 UTC, TuyizeeAnastase commented on src/controllers/product.controller.js
> +    return res.status(200).json({ message: 'product marked' });
change message `Product is available now`

2023-02-23 15:54 UTC, TuyizeeAnastase commented on src/controllers/product.controller.js
> +    console.log('------------',req.body,req.params.productId);
Don't push console

2023-02-23 15:54 UTC, TuyizeeAnastase commented on src/routes/api/product.routes.js
> + checkIfProductExistById,
add middleware to check if the product is not available before made Available.

2023-02-23 15:54 UTC, TuyizeeAnastase commented on src/services/product.service.js
> +  console.log('-------',id);
don't push debugging tools like console

2023-02-24 08:45 UTC, ncutixavier requested changes

2023-02-24 08:45 UTC, ncutixavier commented on src/controllers/product.controller.js
> +  }
- We need to have a global service to update products, and that's what you'll be using to update product availability
- You're just updating, why are you checking availability?
- Write a meaningful message in the catch

2023-02-24 08:45 UTC, ncutixavier commented on src/controllers/product.controller.js
> +     await ProductService.updateProduct(req.body, req.params.productId);
Use this service to update product availability (Marking product)

2023-02-24 08:45 UTC, ncutixavier commented on src/middlewares/product.middleware.js
> +	next();
Let's have separate middleware

2023-02-24 08:45 UTC, ncutixavier commented on src/services/product.service.js
> +  }
We don't need this service, since you're already have the one to update product

2023-02-27 07:12 UTC, irakozetony approved these changes

2023-02-27 08:32 UTC, Abdden approved these changes

2023-02-27 08:38 UTC, fabmukunzi approved these changes

2023-02-28 08:35 UTC, ncutixavier requested changes

2023-02-28 08:35 UTC, ncutixavier commented on src/database/config/config.js
> +      // },
Remove all unnecessary comments

2023-02-28 08:35 UTC, ncutixavier commented on src/routes/api/product.routes.js
> +    deleteProduct
You're missing a middleware to check if the products belong to the seller, and it's already implemented

2023-02-28 08:35 UTC, ncutixavier commented on src/routes/api/product.routes.js
> +  markAvailableProduct,
You're missing validation and middleware to check the owner

2023-02-28 08:35 UTC, ncutixavier commented on src/routes/api/product.routes.js
> +  updateProduct
Missing middleware to check the owner

2023-02-28 08:35 UTC, ncutixavier commented on src/controllers/product.controller.js
> +    await ProductService.updateProduct( isAvailable, req.params.productId);
- You don't have to use `req.params`, when you have a middleware that returns the product
- Validation is needed

2023-02-28 08:35 UTC, ncutixavier commented on src/controllers/product.controller.js
> +     await ProductService.updateProduct(req.body, req.params.productId);
You don't have to use req.params, when you have a middleware that returns the product

2023-02-28 08:35 UTC, ncutixavier commented on src/controllers/product.controller.js
> +     await ProductService.deleteProduct(req.params.productId);
You don't have to use req.params, when you have a middleware that returns the product

2023-02-28 08:35 UTC, ncutixavier commented on src/controllers/product.controller.js
> +       message: 'fail to update product'});
Rephrase this message

2023-02-28 15:22 UTC, ncutixavier approved these changes

2023-02-28 15:30 UTC, ncutixavier commented on src/database/config/config.js
> +    //  url: process.env.FIDELA_REMOTE,
Remove unnecessary comments

2023-02-28 15:43 UTC, ncutixavier approved these changes

2023-02-28 15:46 UTC, merged