feat: implementing public chat
atlp-rwanda/vikings-ec-bn pull request #39
Opened 2023-02-24 13:02 UTC by Abdden

#### What does this PR do?

#### Description of Task to be completed?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?

#### Screenshots (if appropriate)

#### Questions:

2023-02-24 15:18 UTC, Aline096 approved these changes

2023-02-24 16:01 UTC, nshimiyejayd approved these changes

2023-02-24 20:58 UTC, ndatumuremyi approved these changes

2023-02-27 09:58 UTC, TuyizeeAnastase requested changes

2023-02-27 09:58 UTC, TuyizeeAnastase commented on src/services/chat.service.js
> +  }
change how you rename variables message or messages

2023-02-27 09:58 UTC, TuyizeeAnastase commented on src/routes/api/chat.routes.js
> +// router.get('/', protectRoute, ChatController.getMessages);
remove comments

2023-02-27 17:57 UTC, ncutixavier approved these changes

2023-02-27 17:58 UTC, merged