#184347034 implement wishing a product
atlp-rwanda/vikings-ec-bn pull request #42
Opened 2023-02-28 15:06 UTC by Munezeroolivierhugue

### What does this PR do?

Creates Reset password with email endpoints

### Description of Task to be completed?

- Sending email to user
- Getting the token from email
- Reset using the email 

### How should this be manually tested?

1. Clone [repo](https://github.com/atlp-rwanda/vikings-ec-bn.git)
2. Change into the directory vikings-ec-bn
3. Checkout to the branch: feature/add-wishlist-184347034
4. Run the command `npm install` to install all packages
5. Run `npm run seeding`
6. Run `npm run dev`
7. Add products to wishlist at `http://localhost:<port>/api/v1/product-wishes`  URL in Postman

#### What are the relevant pivotal tracker stories?

[#184347034](https://www.pivotaltracker.com/story/show/184347034)

#### Screenshots (if appropriate)

#### Questions:

2023-03-07 12:29 UTC, irakozetony requested changes

2023-03-07 12:29 UTC, irakozetony commented on src/controllers/wishlist.controller.js
> +//adding wishes to wishlist
remove unnecessary comments

2023-03-07 12:29 UTC, irakozetony commented on src/controllers/wishlist.controller.js
> +      if(!product_id){
this code should be in validation

2023-03-07 12:29 UTC, irakozetony commented on src/controllers/wishlist.controller.js
> +  //getting wishes by product
remove unnecessary comment

2023-03-07 12:29 UTC, irakozetony commented on src/services/wishlist.service.js
> +    //get wish by user_id
remove unnecessary comments

2023-03-07 12:30 UTC, Abdden commented on src/middlewares/product.middleware.js
> +    req.product = getProduct;
Please, format your codes correctly.

2023-03-07 12:31 UTC, denislohan requested changes
Rename your commit to match the convetions

2023-03-07 12:35 UTC, irakozetony commented
Change your commit message

2023-03-08 18:15 UTC, irakozetony approved these changes

2023-03-09 06:47 UTC, nshimiyejayd approved these changes

2023-03-09 07:08 UTC, fabmukunzi approved these changes

2023-03-09 08:56 UTC, denislohan approved these changes

2023-03-09 14:58 UTC, ncutixavier approved these changes

2023-03-09 14:58 UTC, merged