#184347048 refactoring public chat
atlp-rwanda/vikings-ec-bn pull request #43
Opened 2023-03-01 18:14 UTC by Abdden

### What does this PR do?

- Adds pagination to the chat functionality on the platform

### Description of Task to be completed?

- Given the user is on the chat, they should be able to see a limited number of old messages.

### How should this be manually tested?

1. Checkout to this branch: `refactor/chat-184347048`
2. Run the command `npm install` to install packages
3. Run `npm run dev`
4. Open your browser and visit `http://localhost:5000/api-docs`

### What are the relevant pivotal tracker stories?

[184347048](https://www.pivotaltracker.com/story/show/184347048)

2023-03-01 19:12 UTC, irakozetony approved these changes

2023-03-02 07:18 UTC, ndatumuremyi approved these changes

2023-03-02 07:20 UTC, nshimiyejayd approved these changes

2023-03-02 07:51 UTC, denislohan approved these changes

2023-03-02 10:43 UTC, TuyizeeAnastase requested changes

2023-03-02 10:43 UTC, TuyizeeAnastase commented on src/controllers/chat.controller.js
> +      const { limit, offset } = req.query;
Add default limit when is empty from user

2023-03-02 10:43 UTC, TuyizeeAnastase commented on src/services/chat.service.js
>      const messages = await Message.findAll({
implement full pagination refer to get All products services

2023-03-02 10:43 UTC, TuyizeeAnastase commented on src/controllers/chat.controller.js
> +        .json({ message: 'Fetched old messages', messages });
in response return total pages,currentPage,total messages and messages

2023-03-02 15:00 UTC, TuyizeeAnastase approved these changes

2023-03-02 15:01 UTC, TuyizeeAnastase requested changes
Tests aren't passing

2023-03-02 15:46 UTC, TuyizeeAnastase approved these changes

2023-03-07 12:13 UTC, ncutixavier approved these changes
LGTM

2023-03-07 12:13 UTC, merged