#184347035 validating productId
atlp-rwanda/vikings-ec-bn pull request #44
Opened 2023-03-02 10:07 UTC by Fidela1

### What does this PR do?

-  Add uuid validation

### Description of Task to be completed?

-  Validate input to match uuid format

###  How should this be manually tested?
 
1. Checkout  to this branch  `refactor/available-product-184347035`
2. Run `npm run dev`

#### What are the relevant pivotal tracker stories?
[#184347035](https://www.pivotaltracker.com/story/show/184347035)

2023-03-02 10:34 UTC, irakozetony approved these changes

2023-03-05 18:53 UTC, nshimiyejayd approved these changes

2023-03-06 14:04 UTC, denislohan requested changes
Commit naming Style went wrong

2023-03-07 11:03 UTC, irakozetony approved these changes

2023-03-07 11:03 UTC, irakozetony commented on src/controllers/product.controller.js
> +   return res.status(200).json({ message: 'Product availability changes successfully' });
Change message to 'Product availability changed successfully'

2023-03-10 18:37 UTC, ndatumuremyi approved these changes

2023-03-12 17:14 UTC, ncutixavier approved these changes

2023-03-12 17:15 UTC, merged