#184347016 Setup docker application
atlp-rwanda/vikings-ec-bn pull request #45
Opened 2023-03-05 20:55 UTC by nshimiyejayd

### What does this PR do?
- This PR implements the setup of docker for backend application

### Description of Task to be completed?
- Setup docker application to run two services  `express server` and `postgres database `

### How should this be manually tested?
- Clone [repo](https://github.com/atlp-rwanda/vikings-ec-bn)
- Checkout to `chore/setup-docker-184347016`
- Set your environment as shown below:
1. `DEV_DATABASE_URL = postgres://<user>:<password>@db:<port>/<db>`
2. `POSTGRES_DB = <db>`
3. `POSTGRES_USER = <user>`
4. `POSTGRES_PASSWORD = <password>`
5. `POSTGRES_VERSION = <version>`
6. `POSTGRES_PORT = <port>`
7. `CONTAINER_PORT = 5000`
- Download and install Docker
- Run `docker-compose up` in terminal

#### What are the relevant pivotal tracker stories?
[#184347016](https://www.pivotaltracker.com/story/show/184347016)

2023-03-06 09:14 UTC, fabmukunzi approved these changes

2023-03-06 09:19 UTC, irakozetony approved these changes

2023-03-06 10:23 UTC, Abdden approved these changes

2023-03-06 14:03 UTC, denislohan requested changes
Wrong Comming naming style

2023-03-07 12:32 UTC, denislohan approved these changes

2023-03-07 12:47 UTC, ncutixavier approved these changes

2023-03-07 12:48 UTC, merged