#184347042 Implement payment with stripe
atlp-rwanda/vikings-ec-bn pull request #46
Opened 2023-03-05 21:02 UTC by irakozetony

### What does this PR do?
Implement payment

### Description of Task to be completed?
User can be able to pay with their credits card, using the stripe api

### How should this be manually tested?
1. Checkout to branch `feature/payment-184347042
2. Login as a buyer and add a few items
3. Send a post request to the endpoint `http://localhost:<5000>/api/v1/payment/create-checkout-session`
4. Then, visit the url returned in the response and enter card details to complete payment

#### What are the relevant pivotal tracker stories?
[#184347042](https://www.pivotaltracker.com/story/show/184347042)

2023-03-10 11:51 UTC, ndatumuremyi approved these changes

2023-03-10 15:29 UTC, fabmukunzi approved these changes

2023-03-12 19:22 UTC, ncutixavier requested changes

2023-03-12 19:22 UTC, ncutixavier commented on src/database/models/sale.js
> +		 */
remove all unnecessary comment

2023-03-12 19:22 UTC, ncutixavier commented on src/routes/api/payment.routes.js
> +paymentRoutes.post('/webhook', express.raw({type: 'application/json'}), webHook
Remove unnecessary comments

2023-03-12 19:22 UTC, ncutixavier commented on src/controllers/payment.controller.js
> +      return res.status(500).json({
Let's refactor this controller by splitting into different methods and middleware if they are

2023-03-12 19:22 UTC, ncutixavier commented on src/controllers/payment.controller.js
> +					name: product.name,
Let's refactor this controller by splitting it into different methods and middleware if they are

2023-03-13 07:15 UTC, ncutixavier commented on src/utils/payment.utl.js
> +				{
change filename

2023-03-13 07:24 UTC, Fidela1 approved these changes

2023-03-13 07:46 UTC, ncutixavier approved these changes

2023-03-13 07:55 UTC, merged