#184557729 Changing order status
atlp-rwanda/vikings-ec-bn pull request #48
Opened 2023-03-07 14:33 UTC by fabmukunzi

### What does this PR do?

Changing order status

### Description of Task to be completed?

A seller should be able to change Product order status and then if all products in the same order are accepted
then order status is changed to accepted and when one of the product order is declined order status become declined
otherwise order is pending

### How should this be manually tested?

1. Clone [repo](https://github.com/atlp-rwanda/vikings-ec-bn.git)
2. Change into the directory **vikings-ec-bn**
3. Checkout to this branch:` feature/change-order-status-184557729`
4. Run the command `npm install` to install packages
5. Run` npm run reset:db`
6. Run `npm run dev`
7. In postman create a patch request **localhost:5000/api/v1/sales/{salesId}/status**

### What are the relevant pivotal tracker stories?

[#184557729](https://www.pivotaltracker.com/story/show/184557729)

2023-03-09 07:14 UTC, nshimiyejayd approved these changes

2023-03-09 07:16 UTC, irakozetony approved these changes

2023-03-09 08:02 UTC, Aline-Uwera commented on src/middlewares/sales.middleware.js
> +  const {id}=req.user
where does this id being used?

2023-03-09 08:11 UTC, Aline-Uwera approved these changes

2023-03-10 10:06 UTC, ncutixavier commented
Please fix all checks @fabmukunzi

2023-03-13 07:25 UTC, ncutixavier requested changes

2023-03-13 07:25 UTC, ncutixavier commented on src/controllers/sales.controller.js
> +      }
Why don't you remove this and return buyerSales?

2023-03-13 07:25 UTC, ncutixavier commented on src/services/order.service.js
> +	console.log("==============",Order)
remove all logs

2023-03-13 12:09 UTC, ncutixavier approved these changes

2023-03-13 12:09 UTC, merged