provide ratings and feedback
atlp-rwanda/vikings-ec-bn pull request #49
Opened 2023-03-08 14:24 UTC by Fidela1

### What does this PR do?

- Provide feedback and ratings

### Description of Task to be completed?

- Provide feedback and ratings for product bought

### How should this be manually tested?

1. clone the [repo](url)
2. Checkout to this branch `feature/provide-ratings-184347035`
3. Run `npm run dev`

### What are the relevant pivotal tracker stories?
[184347035](https://www.pivotaltracker.com/story/show/184347035)

2023-03-14 15:02 UTC, irakozetony approved these changes

2023-03-14 15:08 UTC, irakozetony approved these changes

2023-03-14 15:10 UTC, ndatumuremyi approved these changes

2023-03-15 07:30 UTC, denislohan requested changes
Your endpoint is wrong

2023-03-15 07:31 UTC, denislohan commented
> Your endpoint is wrong

I gave you feedback on the document but you never worked on them, so I will wait for you to fix this

2023-03-15 07:33 UTC, ncutixavier requested changes

2023-03-15 07:33 UTC, ncutixavier commented on src/middlewares/product.middleware.js
> +  console.log(productId)
remove all logs

2023-03-15 07:33 UTC, ncutixavier commented on src/middlewares/ratings.middleware.js
> +      message: 'Rate must be from 0 to 5',});
Ranged from 1-5 not from 0

2023-03-15 07:33 UTC, ncutixavier commented on src/controllers/ratings.controller.js
> +      rate = await RatingService.productRating(ratings);
Rename `productRating` to `createRating`

2023-03-15 07:33 UTC, ncutixavier commented on src/controllers/ratings.controller.js
> +export const getRatingsById = async (req, res) => {
Rename this controller to be specific for getting ratings by specific product

2023-03-15 07:33 UTC, ncutixavier commented on src/middlewares/ratings.middleware.js
> +      next();
How do you know if the order has completed? because I can't see any condition

2023-03-15 07:33 UTC, ncutixavier commented on src/routes/api/rating.route.js
> +);
- Change the endpoint as I showed you yesterday
- Do you know why you check if the seller owns a product? multiple users can view the product ratings. You don't need to restrict them

2023-03-15 16:59 UTC, ncutixavier requested changes

2023-03-15 16:59 UTC, ncutixavier commented on src/controllers/ratings.controller.js
> +    return res.status(201).json({ message: 'Ratings retrived successfully', ratings: ratings });
Update status code

2023-03-15 16:59 UTC, ncutixavier commented on src/middlewares/ratings.middleware.js
> +  next();
Rate should be ranged from 1-5

2023-03-15 17:49 UTC, ncutixavier commented on src/middlewares/ratings.middleware.js
> +  if (rate < 1 || rate > 5) {
1 and 5 should be included

2023-03-15 18:26 UTC, ncutixavier approved these changes

2023-03-15 18:47 UTC, merged